eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8081
spring:
  application:
    name: phery-web
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/taotao
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver